### ISSUE TITLE
Optional store configurations in default intellij preferences

### ISSUE THREAD

**Issue by ldriscoll** [jshiell/checkstyle-idea#233]
We run a lot of projects and would love it if we could store the checkstyle configurations globally, and then enable them on a specific project.

**Comment by jshiell** [comment]
No promises, but that does seem a great idea - it'll take a bit of thought on how to allow both project & global settings, but I imagine it would be useful for many people - thanks for the suggestion!

**Comment by stroeller** [comment]
As it is now, it is a bit confusing since one in default settings can add an entry and set it to active. But it is never used (as far as I can tell). We are also very interested in having this feature implemented.
![cs-idea-default-settings](https://cloud.githubusercontent.com/assets/20083889/16257706/70b2fbac-385a-11e6-9346-c6638c51a16f.PNG)

**Comment by jshiell** [comment]
That's a very fair argument - I didn't even realise it was shown there. Fixing this sounds like a separate issue, but shouldn't be too hard. I hope 😄

**Comment by jshiell** [comment]
On the _default settings_ front, they appear to work for me. For instance, if I edit _default settings_ to add a config and set it to active, and I then create a new project, the default settings are present in the new project. @stroeller could you please let me know what part of this doesn't work for you, and IDEA version/OS etc? As it seems a bit odd.

(This is still different to have project-wide configuration, of course, which I plan to get on to at some point when life calms down.)

**Comment by dod38fr** [comment]
On my side, I've installed and configured checkstyle plugin after project creation. I've experienced the same issues as @stroeller .

Turns out checkstyle configuration of a module must be changed for checkstyle plugin to use a custom configuration.

(Seen with idea 2016.2.2 and checkstyle-idea 4.31.0)

HTH

**Comment by stroeller** [comment]
From what we have noticed, it works like this: If you create a new project when being in a project with checkstyle configuration, those default settings will be copied to a new project and you don't have to manually add the checkstyle configuration.
If you on the other hand create a new project from an "old" project, without checkstyle configuration, there will be no default checkstyle configuration in the new project.

**Comment by jshiell** [comment]
Closing this, as the implementation relies on the project template functionality of IDEA, with all the limitations that implies.
