### ISSUE TITLE
Way of donation

### ISSUE THREAD

**Issue by dongjinleekr** [jshiell/checkstyle-idea#257]
I greatly appreciate your effort to develop and maintain this plugin. It has been and is greatly helping my team and me everywhere. All my workmates want to thank you.

I need some way to express my humble appreciation. Could you add any donation method (e.g., Paypal) on your github project page? I tried to find it but failed.

**Comment by jshiell** [comment]
Thanks very much for your kind words - you made my day!

I don't accept donations, mostly because I see this as being my way of contributing to the open source community - to which I am deeply in debt, as both my job & hobbies would be much less pleasant without the many OS projects I use.

But I do deeply appreciate the offer, and the knowledge that this is of help to people is absolutely smashing - thank you!
