### ISSUE TITLE
No rulesets in plugin GUI

### ISSUE THREAD

**Issue by MEZk** [jshiell/checkstyle-idea#274]
Hello!

**Problem:**

 I cannot select any loaded rulesets in plugin gui because they are not displayed:

<img width="386" alt="screen" src="https://cloud.githubusercontent.com/assets/7242568/19517529/c694aa0a-9612-11e6-8e54-c2d34b18b8ad.png">

**Environment:**

IntelliJ IDEA Ultimate 2016.2.5 build 162.2228.15.
OS: OS X 10.11.2 (15C50)
Plugin version: 4.32.2.

**Comment by jshiell** [comment]
Hey - thank for your feedback! Could you please attached a screenshot of the configuration dialogue, and also tell me if any exceptions are being thrown when you try to access this? Thank you!

**Comment by MEZk** [comment]
<img width="386" alt="config" src="https://cloud.githubusercontent.com/assets/7242568/19576239/4a63faaa-9723-11e6-89aa-e119bb9eae90.png">

Thanks in advance.

**Comment by jshiell** [comment]
Thank very much - I'll have a poke around as soon as I'm able; there may be a bit of a delay though, as I've currently broken my workstation and need to get it rebuilt - sorry!

**Comment by MEZk** [comment]
@jshiell 
I reolved the problem on my local machine:
1) Deleted Checkstyle IDEA plugin.
2) Invalidated IDEA's cache and restarted the IDEA.
3) Installed Checkstyle IDEA plugin.
4) Added xml-config for Checkstyle-IDEA plugin.
5) Again invalidate IDEA's cache and restarted IDEA.
6) Finally made the plugin works correctly.

It might be a bug of IDEA plugin platform itself.

**Comment by jshiell** [comment]
Well, you've done better than I have. I've made no progress, nor can event explain it in the light of your solution.

Both UI elements should read from the same configuration model. There is an event notification to the combo box when the model changes, so there's the possibility of a breakage there, but given the model is pre-populated on instantiation I'd expect this case to be resolved after a restart of the IDE.

It's certainly possible it's an IDEA thing, as the model in question relies on the plugin API for [de]serialisation, but it's certainly not cut & dry.

As your problem is solved I'll close this for the present, and reopen it if another incident is reported.  Likewise, if you see it again please re-open and I'll return to scratching my head about it.

Thanks again for your report & hep!
