### ISSUE TITLE
EmptyBlockCheck is not marked by plugin

### ISSUE THREAD

**Issue by igorwojda** [jshiell/checkstyle-idea#357]
com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck

```
        if (eventBus != null){

        }
```

**Comment by igorwojda** [comment]
Actually, I discovered that error check is performed, but errors are not marked in code
![image](https://user-images.githubusercontent.com/530122/32572156-aba24cbe-c4c1-11e7-9528-608bcef0d015.png)


BTW It is related to
https://github.com/jshiell/checkstyle-idea/issues/356

**Comment by jshiell** [comment]
Thanks for the report.

This is probably due to the error reconciliation - Checkstyle reports errors as line:column, but IDEA stores the documents as a parsed tree. We do some black magic to try and determine the mapping, but they sometimes fall through the cracks, especially when we can't find an exact element. In this case you'll tend to see the error in the gutter but not in the code.

There's a few use cases here, but unless Jetbrains offer their own API for lookup we're unlikely to ever get a perfect mapping here.

**Comment by jshiell** [comment]
Closing as we're dependent on IDEA's file model here for error locations.
