### ISSUE TITLE
Create separate inspections for warning and error?

### ISSUE THREAD

**Issue by TWiStErRob** [jshiell/checkstyle-idea#369]
> Limitations:
> CheckStyle errors and warnings from the inspection are both shown at a single level, as IDEA will only allow one warning level for an inspection.

Looking at https://github.com/jshiell/checkstyle-idea/blob/master/src/main/java/org/infernus/idea/checkstyle/CheckStyleInspection.java#L115

Wouldn't it be easy to create two inspections, and change only this filter in each impl?

**Comment by jshiell** [comment]
If we did so we'd end up running the check twice (or more, since we'd have to cover info at well). This can be quite expensive, as for files in flux we need to create a temporary file structure for Checkstyle to scan. As such, if we were to go down this path we'd need to used some shared resource between the inspections to only run the check once, which runs into the wonderful world of locking between potentially multiple inspection threads. Fun fun. In short it would increase complexity substantially for minimal gain, and is something I'd need a lot of convincing to support.

Interestingly, we do return to IDEA the 'type' of the error - https://github.com/jshiell/checkstyle-idea/blob/4005806749f6dc6e906e3ad94b1eb7ac4e4f58cc/src/main/java/org/infernus/idea/checkstyle/checker/Problem.java#L61 - however, it's not a direct mapping (and may have changed since implementation) so open to suggestions on tweaks here.

**Comment by TWiStErRob** [comment]
It's a nice to have for now, I can't find any good argument yet. I was kind of expecting this answer.

I would say the performance hit could be acceptable with "trivial"-ish implementation (making sure parallel CS runs don't mess with each other), if it's flagged as an experimental feature. For this there must be an option to enable (disabled by default), which I guess is provided as Inspections have set-up. At least the ability is there if the user chooses to use it.

Just to clarify the performance hit you would expect is not the actual running of CS or filtering the results, but preparing the files to run it. Can you please clarify what "for files in flux" means?

**Comment by jshiell** [comment]
Files in flux = files which have been altered in some way, and hence may not be flushed to disk. Because Checkstyle operates on the filesystem we can't just hand over the buffer, but need write the buffer contents to a temporary file (as obviously we can't force-save for the user). Further, we need to build a temporary dir structure that matches the layout of the file in question so that package checks and the like continue to work.
