### ISSUE TITLE
Intellij Ultimate 2018.1 does not import checkstyle config

### ISSUE THREAD

**Issue by mgilgar** [jshiell/checkstyle-idea#391]
I could not see that Ultimate 2018.1.1 is supported in the readme, any way, that may be a feature that the author may want to implement at some point.

Steps to reproduce:
From Intellij Ultimate Idea 2018.1.1 (build 181.4445.78.9 running on jre  1.8.0_152
I install the plugin checkstyle-idea 5.18.6 using preferences window.
Then I go to Preferences/editor/code style/java
I click the small wheel close to "Scheme" dropdown.
I choose import scheme and then "checkstyle configuration"
I select a file I downloaded from: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml
(That file works alright when I use gradle to check the format of the project)
Then I click open
And I see the "Loading..." message and after a while it does not disappear.
If after a whileI click Apply or OK, I go back to the project, but the code format option does not format in a different way than before, so when I run gradle build, I still get a lot of errors due to the differences between the two code style standards.

**Comment by jshiell** [comment]
We support all release versions newer than the minimum, unless otherwise noted. I do my work in 2018.1.x, and although the build against 2016.1 it's generally tested on whatever I'm using (currently 2018.1.1 Ultimate). As far as I know there are no 2018.1-specific issues.

The code importer was a contribution to the code-base so I'm not hugely familiar with it. I do know it's incomplete - some elements aren't handled, and some don't translate to IDEA and hence are ignored. Hence I fear we'd need concrete examples to make any sensible comment.

If you see errors, we can certainly look at that. If nothing is popping up then it's worth checking the IDEA log to see if anything has been caught (`Help` -> `Show log in Finder` on the Mac version, probably something similar elsewhere).

**Comment by zentol** [comment]
I ran into the same issue in 2018.3; none of the importers seem to be working. Migrating the importers to work against `JavaCodeStyleSettings` instead of the (partially deprecated) `CodeStyleSettings` did the trick, for me at least.

Against the 2018 SDK there's also a compile error in `CheckStyleModuleConfiguration`; `@Storage` no longer as the `id` field.

**Comment by tsjensen** [comment]
1. Make sure you use a specific version of the XML file, as the lastest master may refer to features which have not yet been released, for example https://github.com/checkstyle/checkstyle/blob/checkstyle-8.14/src/main/resources/google_checks.xml
2. Make sure that you select the same version in the Checkstyle version dropdown in the IDEA settings dialog that you used in the URL. Otherwise the file will be incompatible.

Versions which are not in the dropdown are not supported.

**Comment by tsjensen** [comment]
Also note that the Google checks in particular are built-in, so you can just activate them from the settings page and you will always get the XML version matching your selected runtime automatically.

**Comment by jshiell** [comment]
Closing this as we now build against API 2018.1.8 (181.5684.4), and the code style settings were migrated to the more modern API. Feel free to reopen if I've misjudged this fix.
