### ISSUE TITLE
Could this plugin be used to display the data in a checkstyle.xml file for any arbitrary project / IntelliJ IDE?

### ISSUE THREAD

**Issue by deinspanjer** [jshiell/checkstyle-idea#405]
Right now, it seems that the plugin is only able to be installed on IDEA, not GoLand or other IntelliJ IDEs. (Makes sense, the word IDEA is in the name!)

I've recently started working with the https://github.com/alecthomas/gometalinter tool in a project that I moved from IDEA to GoLand.  gometalinter has an argument that causes it to output the results in a checkstyle format XML document.

It would be really great if that could be consumed by the IDE and displayed as markups in the editor window rather than just a big list of log statements.

Thoughts about feasibility?  I'd be happy to try to help out on changes if it is a reasonable approach.

**Comment by jshiell** [comment]
Sounds like a great idea - I fear this plugin isn't going to be much help to you, however. We never see the Checkstyle XML - rather, we integrate directly with the same Checkstyle API the CLI tool uses, and listen to error events. We then render those as a tree. Hence the only bit you could perhaps benefit from reusing is the display tree/toolwindow, and that is so small as to be better to reimplement or copy.

Very happy to be convinced otherwise if you've insights I've missed, but I suspect this project won't be of much help. Sorry!

**Comment by deinspanjer** [comment]
Thank you very much for the feedback. :)
