### ISSUE TITLE
error when name of directory in path ends with an exclamation point

### ISSUE THREAD

**Issue by kevin-wayne** [jshiell/checkstyle-idea#412]
I believe there is a bug that arises when the path to a third-party-checks jar file contains a subdirectory name that ends with an exclamation point, resulting in a "The Checkstyle rules file could not be parsed" error. The likely reason is that the syntax for specifying a file within a jar also uses an exclamation point, and the wrong exclamation point gets parsed for that purpose.

In the example below, the project folder name is "hello!"

<img width="932" alt="screen shot 2018-09-21 at 8 30 58 pm" src="https://user-images.githubusercontent.com/5225666/45911167-148d6400-bdde-11e8-9bd8-6d359f376bd7.png">

<img width="873" alt="screen shot 2018-09-21 at 8 30 18 pm" src="https://user-images.githubusercontent.com/5225666/45911171-1c4d0880-bdde-11e8-93f3-99aa9a824f01.png">

**Comment by jshiell** [comment]
Thanks for the report. Indeed, sound like an escaping problem - I'll add it to the todo list.

**Comment by jshiell** [comment]
You were entirely right - we oddly enough detected presence in a JAR based on `.jar!/`, yet split on `!/`. Those should now align. This should be fixed in 5.24.0.

If this fix doesn't resolve your problem please reopen and please attach your `checkstyle-left.jar` and `checkstyle-cos126.xml` files. The area is a bit edge-casey, although I'm pretty sure this fix should cover it.

**Comment by kevin-wayne** [comment]
Thanks, unfortunately it leads to the same error message as before. Here's a zip file containing checkstyle-cos126.xml and checkstyle-lift.jar. (Github doesn't support uploading those file types.)

[wayne.zip](https://github.com/jshiell/checkstyle-idea/files/2761388/wayne.zip)

**Comment by jshiell** [comment]
Apologies - I obviously buggered up my test case. Thanks for those files - I'll [hopefully] have another go at this weekend and hopefully come up with a better result.

**Comment by jshiell** [comment]
So, good news and bad news.

The good news - there was a bug in JAR reference handling in the plugin, and I think I did fix it in the previous commit.

The bad news - this isn't that bug. This appears to be a problem with core Checkstyle, in particular regarding the handling of the `checkstyle_packages.xml` class in extensions. 

The worse news - we don't have any access to the part of the code that does this so it'll need to be fixed in [Checkstyle](https://github.com/checkstyle/checkstyle/) itself. Sorry.

On the upside, you have a nice case to reproduce it:
```
$ mkdir 'test-configs/wayne!'
$ unzip -d test-configs/wayne\! ~/Downloads/wayne.zip
$ java -Dsuppressions=test-configs/wayne\!checkstyle-suppressions.xml -Dbasedir=test-configs/wayne\! -cp ~/Downloads/checkstyle-8.16-all.jar:test-configs/wayne\!/checkstyle-lift.jar com.puppycrawl.tools.checkstyle.Main -c test-configs/wayne\!/checkstyle-cos126.xml src
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to open jar:file:/Users/jshiell/Projects/checkstyle-idea/test-configs/wayne!/checkstyle-lift.jar!/checkstyle_packages.xml
	at com.puppycrawl.tools.checkstyle.PackageNamesLoader.processFile(PackageNamesLoader.java:175)
	at com.puppycrawl.tools.checkstyle.PackageNamesLoader.getPackageNames(PackageNamesLoader.java:146)
	at com.puppycrawl.tools.checkstyle.Checker.finishLocalSetup(Checker.java:428)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:194)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:386)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:313)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:180)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: java.nio.file.NoSuchFileException: /Users/jshiell/Projects/checkstyle-idea/test-configs/wayne
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)

$ mv test-configs/wayne\! test-configs/wayne
$ java -Dsuppressions=test-configs/wayne/checkstyle-suppressions.xml -Dbasedir=test-configs/wayne -cp ~/Downloads/checkstyle-8.16-all.jar:test-configs/wayne/checkstyle-lift.jar com.puppycrawl.tools.checkstyle.Main -c test-configs/wayne/checkstyle-cos126.xml src
# different exception here as I have my paths fscked up, but you get the point
```
