### ISSUE TITLE
Balance attr doesn't support now.

### ISSUE THREAD

**Issue by peterarsentev** [jshiell/checkstyle-idea#477]
Hello. I have checkstyle rules with tag property and attr balance. When I try to import this rule I have an exception.
`com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - Attribute "value" is required and must be specified for element type "property".:9:70
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:318)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:283)
`
if I replace balance attr to value It works, but I suggest that is not right way how to fix it.

Was
`<property name="fileExtensions" balance="java, properties, xml"/>`
is
`<property name="fileExtensions" value="java, properties, xml"/>`
Could you support old scheme too?
Thanks.

**Comment by jshiell** [comment]
Good morning. We support whatever Checkstyle itself supports, and allow you to select the version most appropriate to needs. We have no control over this - as you can see, the exception is from Checkstyle itself, and the plugin just passes it on. 

AFAIK `property` has always used `name` and `value`, but if a supported version of Checkstyle did support another syntax then you should just need to select it in the plugin preferences in order to use such a feature.
