### ISSUE TITLE
When "file contains tab characters" banner is visible, no highlighting

### ISSUE THREAD

**Issue by javaerb** [jshiell/checkstyle-idea#489]
Specifically, this is when a file-level error banner is shown. Does not happen when warning-level banner. Seems to suppress all inspection highlighting, not just checkstyle. Green checkmark is shown. 

IntelliJ IDEA 2019.3.4 Ultimate

**Comment by jshiell** [comment]
Thanks for the report. Does this happen with all plugins, or just CS-IDEA?

We rely on IDEA to call the inspection, and process the results, so there's no obvious vector for the plugin to break this. But never say never.

**Comment by javaerb** [comment]
Don't know how to get it with other plugins. Sounds like an IDEA thing. WHat is the proper name for that banner?

**Comment by jshiell** [comment]
Curiously enough, this doesn't appear to happen for me. I'm also on 2019.3.4U, on MacOS 10.13. 
<img width="1055" alt="Screen Shot 2020-04-20 at 16 47 33" src="https://user-images.githubusercontent.com/1030482/79771565-e14ae800-8326-11ea-8139-1caaadfa5ce4.png">

To set up the above I just inserted a few tab characters, turned on the built-in whitespace check inspection, and restarted the IDE to make sure it wasn't keeping previous state.

I'm honestly unsure as to what the bar is called - I know you IDEA uses it for `Problem`s returned from an inspection where the target element is the `PsiFile`, rather than a particular element with in, but the UI logic is all inside IDEA.

**Comment by javaerb** [comment]
In your image, you have checkstyle set as warnings, not errors, which is why you are not seeing it. See https://youtrack.jetbrains.com/issue/IDEA-238254

**Comment by jshiell** [comment]
Sorry for the delay. I can now reproduce it, but I can do it if I change the error level of IDEA's `problematic whitespace` inspection to be `ERROR` rather than `WARNING`. I don't need to make any Checkstyle changes, and if I change the `problematic whitespace` inspection back to `WARNING` then the Checkstyle inspection results reappear.

It occurs with 2020.1 as well, by the way.

I can't see anything in the plugin that would case this - the inspection interface is pretty simple, we just return a list of problems with a level enum in them. And given the above, I strongly suspect this is an IDEA issue rather than a plugin issue.
