### ISSUE TITLE
5.67 lost configuration properties

### ISSUE THREAD

**Issue by keturn** [jshiell/checkstyle-idea#573]
converting from this older checkstyle-idea.xml https://github.com/MovingBlocks/Terasology/blob/develop/.idea/checkstyle-idea.xml

it no longer saves the `samedir` property of the configuration.

Adding and removing the configuration from the GUI doesn't improve it. After restarting if I edit its properties again, the value is blank.

—and congratulations on the 1000th commit! :tada:

**Comment by jshiell** [comment]
Thanks 🎉 Although it looks like the 1000th made me get sloppy - I _may_ have been rushing before I headed off on holiday for a week, and I _may_ have completely hosed the properties configuration. Luckily, this made it easy to fix once I realised what a fool I had been 🤦 

Sorry for the hassle, should be fixed in 5.67.1!
