### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by wangqi-123** [jshiell/checkstyle-idea#579]
Excuse me，I have a question，How did you solve the problem of incompatibility between the plugin and the jdk version embedded in the development tools? For example, my development tool is the IDEA2018 version, the embedded JDK version is 1.8, and checkstyle requires the use of gradle7.3.1 to build, and gradle7.3.1 requires the JDK version to be 11, then in this case, I type checkstyle Wrapped on my IDEA2018, it doesn't work well, if I downgrade the version of gradle, there will be some APIs that don't exist? How do you solve the compatibility problem of different versions of IDEA? That is, how did you adapt to IDEA2021 at the same time as IDEA2018?

**Comment by jshiell** [comment]
We don't, I fear. The earliest IDEA we currently support is 2021.1.3, due to exactly these sort of problems - and I suspect we'll have to upgrade that in the not too distant, due to deprecations in the newer SDKs. My general rule is to try and keep compatibility for versions 1 to 2 years old, but it does depend on the changes IDEA make to the SDK.

The way I've seen other plugins do it is by publishing multiple versions, and running mulitple branches to maintain compatibility with SDK. This is pretty maintainence heavy, so it's not something I've adopted.

If you wish to do your own personal build then you could try downgrading Gradle - AFAIK we don't use any features tied to version 7, but I can't promise it'll work. I fear the easiest solution to your problem will be updating to a newer version of IDEA - sorry.
