### ISSUE TITLE
support checkstyle_packages

### ISSUE THREAD

**Issue by kdh6429** [jshiell/checkstyle-idea#610]
I am trying to write a separate detection logic using AbstractCheck. To apply this, I need to add related information to checkstyle_packages.xml, but it seems that only checkstyle.xml file is imported from this library. Is there any part I missed?
https://checkstyle.sourceforge.io/config.html#Packages

**Comment by jshiell** [comment]
Hmm. As far as I know, the plugin should handle this - primarily because, other than adding extra checks to the classpath, we don't do anything - Checkstyle itself locates and parses the file.

Sanity check - your check is in a JAR file, the `checkstyle_packages.xml` is in the root of the JAR file, and it has been added to the third-party checks classpath in the CS-IDEA plugin options?

**Comment by jshiell** [comment]
Closing due to no further information.
