### ISSUE TITLE
Allow multiple runs with different rule files

### ISSUE THREAD

**Issue by jshiell** [jshiell/checkstyle-idea#7]
Currently it is only possible to select one XML check file and have the
project/whatever checked against this very file.

It could come handy, if one could select and use multiple files (and thus
running checkstyle multiple times without losing the results of the
previous run(s).)

Best regards,

Mihai

This feature is especially useful for Android development, where we usually want to use the standard sun-checks.xml but on top of that, Android specific checks.

**Comment by Naros** [comment]
I am somewhat surprised at the age of this enhancement and yet it would certainly be worthwhile for projects.  For example, the Hibernate project uses multiple checkstyle configurations where we have segregated fatal from non-fatal concerns allowing us to potentially execute checkstyle on CI at different points in the CI workflow.  The problem is IJ does not allow us to select multiple configurations as active and thus we either must explicit run all checkstyle configurations manually prior to commit/push or deal with the problem reactively.  Of course, having IJ run multiple checkstyle configurations that are active would help elevate this explicit step on the developer and improve the development experience imo.

**Comment by jshiell** [comment]
For various reasons this project is essential in maintenance mode. What work I do is focused on keeping things working, and fixing bugs. Hence this is unlikely to be addressed in the foreseeable future.

Contributions are, of course, very welcome.

**Comment by jshiell** [comment]
This was added in 5.64.0. Whoops.
